title: Wifi Santiago
email: contato@cubekode.com
description: > 
  Quais os protocolos de criptografia de redes wifi é o mais utilizado
  em uma cidade pequena? WEP ou WPA? quem utiliza WPS? Capturamos diariamente
  as redes wifi disponíveis na cidade de Santiago e disponibilizamos publicamente.
baseurl: ""
url: ""
exclude: ["node_modules", "bower_components", "bower.json", "Gemfile.lock", "Gemfile",
  "Gruntfile.js", "package.json", "src"]
markdown: kramdown
